### ISSUE TITLE
Bumblebee.Jwt.JwtPlugin

### ISSUE THREAD

**Issue by duyanming** [IKende/Bumblebee#45]
版本 bumblebee.1.3.2
启动bumblebee -->
--->启用jwt插件，--->然后关闭jwt插件
--->停止 bumblebee  --->再启动 无法进入系统
![image](https://user-images.githubusercontent.com/17999146/71638188-240f8400-2c94-11ea-84aa-f4fc882c8249.png)
```csharp
[12:39:58] [Error] Gateway 26472473813843969 ::1 GET /__system/bumblebee/plugins.html process error Method not found: 'Void Bumblebee.Gateway.IncrementRequestCompleted(BeetleX.FastHttpApi.HttpRequest, Int32, Int64, Bumblebee.Servers.ServerAgent)'.@   at Bumblebee.Jwt.JwtPlugin.Execute(EventRequestingArgs e)
   at Bumblebee.Plugins.Pluginer.Requesting(HttpRequest request, HttpResponse response)
   at Bumblebee.Gateway.OnRequest(Object sender, EventHttpRequestArgs e)
```

**Comment by IKende** [comment]
看来是jwt插件没有编译对应的新版本导致....

**Comment by IKende** [comment]
暂可以删除目录下的`Gateway.json`恢复默认设置即可运行

**Comment by duyanming** [comment]
谢谢！

**Comment by IKende** [comment]
update to 1.3.3.8
